### PR TITLE
sign in success respond with same payload as request

### PR DESCRIPTION
**Pull request by imranariffin**
#25

### CODE REVIEW

**Review by cglotr — DISMISSED** [review]
We should update the [docs](https://github.com/hooligram/hooligram-docs) as well. Otherwise, LGTM.

**Comment by imranariffin** [comment]
Ok will do it tomorrow morning in sha Allah. Gotta go to bed now haha

**Comment by cglotr** [comment]
> in sha Allah

What kind of _in sha Allah_ is this? The kind that means _"Yeah, not gonna do this LOL"_ or the [legit](https://en.wikipedia.org/wiki/Inshallah) one hahahaha

**Comment by imranariffin** [comment]
Actually, I might as well just do it before going to be bed. btw that was a legit one haha.

Merged docs https://github.com/hooligram/hooligram-docs/pull/2

**Pull request merged**
