### PR TITLE
Feature/twilio review

### PR DESCRIPTION
**Pull request by cglotr**
#20

### CODE REVIEW

**Review by imranariffin — APPROVED** [review]
lgtm overall. 

Aside: Now I started to realize I need to review/study on some go syntaxes specifically on interface, methods, pointers.
I also I need to go over the whole codebase again to get better understanding.

**Comment by imranariffin** [comment]
Maybe next week you can give a refresher on the codebase, @cglotr .

**Comment by imranariffin** [comment]
Btw, just to be 100% sure. This doesn't change the behavior of the endpoints, right? (except for the fix by 66a9010)

**Comment by cglotr** [comment]
> Btw, just to be 100% sure. This doesn't change the behavior of the endpoints, right? (except for the fix by [66a9010](https://github.com/hooligram/hooligram-server/commit/66a9010067d138073f4e94c80f65975e7b475f2a))

@imranariffin yes, the supported API will remain the same. Actually, there's only one non-impact change. Now the server will include `"errors"` in all `*_FAILURE` actions.

**Comment by imranariffin** [comment]
I see. Good to know.

**Pull request merged**
